INSERT INTO CATEGORY (NAME) VALUES ('BOARD GAME');
INSERT INTO CATEGORY (NAME) VALUES ('STUFFED TOY');
INSERT INTO CATEGORY (NAME) VALUES ('TRANSPORT');
INSERT INTO CATEGORY (NAME) VALUES ('SPORT');
INSERT INTO CATEGORY (NAME) VALUES ('CLOTHES');
INSERT INTO CATEGORY (NAME) VALUES ('DOLL');

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('CHESS', 'WOODEN CHESS', '5000', 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('BEAR', 'BROWN BEAR', '2000', 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('RABBIT', 'RABBIT WITH CARROT', '2000', 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('ELEPHANT', 'SMALL ELEPHANT', '3000', 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('TRAIN', 'WOODEN TRAIN', '3000', 3);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID) VALUES ('CAR', 'SMALL RED CAR', '2500', 3);